// notesuireact/src/navbar.tsx
import React from "react";
const Navbar = ()=>{
    return(
        <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
            <div className="container-fluid">
                <a className="navbar-brand" href="/home"> Navbar </a>
                <button className="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span className="navbar-toggler-icon"></span>
                </button>
                <div className="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul className="navbar-nav me-auto mb-2 mb-lg-0">
                        <li className="nav-item">
                            <a className="nav-link" aria-current="page" href="/home">Home</a>
                        </li>
                        <li className="nav-item">
                            <a className="nav-link" href="/signup">signup</a>
                        </li>
                        <li className="nav-item">
                            <a className="nav-link" href="/signin" >signin</a>
                        </li>
                        <li className="nav-item">
                            <a className="nav-link" href="/home" >home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    );
}

export default Navbar;

// NotesUI/src/app/WebModule/navbar/navbar.component.ts
import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent{

}

<nav class="navbar navbar-expand-lg navbar-expand-md navbar-dark bg-dark">

  <a class="navbar-brand p-3" [routerLink]="['']"><i class="bi bi-journals m-2"></i>Notes</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav m-2">
      <li>

        <button class="btn btn-primary  m-1 " [routerLink]="['/login']"><i class="bi bi-box-arrow-in-right m-1"></i>Login</button>
      </li>
      <li>
        <button class="btn btn-warning m-1" [routerLink]="['/signup']"><i class="bi bi-brush m-1"></i>Signup</button>
      </li>
    </ul>
  </div>
</nav>
