// notesuireact/src/pages/todolist/todolist.tsx
import axios from "axios";
import React, { useEffect, useState } from "react"
import Cookies  from "js-cookie";
import jwt_decode, { JwtPayload } from "jwt-decode";
import { Link } from "react-router-dom";
require("./todolist.css")
const TodoList=()=>{
    const [todolist,setTodolist]=useState([] as any);
    const [userId,setUserId]=useState(null);
    const [addTask,setAddTask]=useState(false);
    const [updateTake,setUpdateTask]=useState(false);
    const [search,setSearch]=useState("");
    const [todoData,setTodoData]=useState("");
    const [updateData,setUpdatedata]=useState("");
    const [updateUserId,setUpdateUserId]=useState(0);
    const [updateId,setUpdateId]=useState(0);
    const handleAddTask=()=>{
        setAddTask(true);
    }
    const handleAddedTask=()=>{
        const JWT=Cookies.get('user');
        setAddTask(false);

        axios.post("http://localhost:8080/todolist/",{
            userId:userId,
            todoData:todoData
        },{ headers: {"Authorization" : `Bearer ${JWT}`} }).then(res=>window.location.reload()).catch(err=>console.log(err));
    }
    const searchTask=(event:any)=>{
        if(event.target.value==="")
        {
            getUserId();
        }
        else
        {
            const JWT=Cookies.get('user');
            axios.get(`http://localhost:8080/todolist?query=title:${event.target.value},`,{ headers: {"Authorization" : `Bearer ${JWT}`} }).then(res=>{
                setTodolist([]);
                res.data.map((data:any)=>{
                    setTodolist((element: any)=>[...element,data]);
                })
                console.log(res.data);
                
            })

        }

    }
    const handleSearch=(event:any)=>{
        setSearch(event.target.value);
        searchTask(event);

    }
    useEffect(()=>{
        getUserId();
        console.log("Came here")
    },[]);
    const getUserId=()=>{
        const JWT=Cookies.get('user');
        if(JWT)
        {
            let email=jwt_decode<JwtPayload>(JWT);
            axios.get("http://localhost:8080/user/"+email.sub,{ headers: {"Authorization" : `Bearer ${JWT}`} }).then(res=>{
                setUserId(res.data);
                getTodoList(res.data);
            })

        }
        
    }
    const getTodoList=(userId:number)=>{
        const JWT=Cookies.get('user');
        axios.get("http://localhost:8080/todolist?query=,",{ headers: {"Authorization" : `Bearer ${JWT}`} }).then(res=>{
            setTodolist([]);
            res.data.map((data:any)=>{
                setTodolist((element: any)=>[...element,data]);
            })
            console.log(res.data);
            
        })
    }
    const handleUpdatedTask=()=>{
        const JWT=Cookies.get('user');
        setUpdateTask(false);
        axios.put("http://localhost:8080/todolist/"+(updateId),{
            userId:updateUserId,
            todoData:updateData
        },{ headers: {"Authorization" : `Bearer ${JWT}`} }).then(res=>window.location.reload());
    }
    const handleUpdateTask=()=>{
        setUpdateTask(true);
    }
    const deleteTask=(data:any)=>{
        const JWT=Cookies.get('user');
        axios.delete("http://localhost:8080/todolist/"+data.id,{ headers: {"Authorization" : `Bearer ${JWT}`} }).then((res)=>window.location.reload()).catch(err=>{
            console.log(err);
        });
    }
    const handleTodoData=(event:any)=>{
        setTodoData(event.target.value);
    }
    const updateTask=(data:any)=>{
        handleUpdateTask();
        setUpdatedata(data.todoData);
        setUpdateUserId(data.userId);
        setUpdateId(data.id);

    }
    const handleUpdateData=(data:any)=>{
        setUpdatedata(data.target.value);
    }
        return (
        <>
        <div className="container p-5">
  <div className="input-group">
  <input className="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" value={search} onChange={handleSearch}/>
    <button  className="btn border-0"><i className="bi bi-search" style={{fontSize: '1.5rem'}}></i></button>
  </div>
    <div   className="container border-dark border-3 rounded " style={{marginTop:'3rem'}}>
  {todolist.length===0 &&  <h5 className="border-dark bg-danger rounded opacity-25 display-6" >not found ! </h5> }
      
  </div>
  {addTask &&
  <form>
  <button  className="btn btn-outline-dark " onClick={handleAddedTask}>Add Tasks</button>
    <div>

      <input  style={{margin:'1rem',textAlign: 'center', width: '12rem', height: '2rem', boxShadow:' 0 0 5px rgba(0, 0, 0, 0.3)', backgroundColor: '#fafafa'}}
              type="text"
              id="noteUpdateHeading"
              name="noteHeading"
              value={todoData}
              onChange={handleTodoData}
              required
              minLength={1}/>


      <div className="text-warning m-2" >Task is required</div>
    </div>
  </form>
}
{updateTake &&
  <form>
  <button type="submit" className="btn btn-primary" onClick={handleUpdatedTask} >Update task</button>
    <div>

      <input  style={{margin:'1rem',textAlign: 'center', width: '12rem', height: '2rem', boxShadow: '0 0 5px rgba(0, 0, 0, 0.3)', backgroundColor: '#fafafa'}}
              placeholder="add tasks here"
              type="text"
              id="noteHeading"
              name="noteHeading"
              value={updateData}
              onChange={handleUpdateData}
              required
              minLength={1}

      />

      <div className="text-success m-2" >Task is required</div>
    </div>
    
  </form>}
 {!addTask && <button type="submit" className="btn btn-dark" onClick={handleAddTask}>Add task</button>}
  {todolist.length>0 &&
  <table className="table table-light"  style={{marginTop: '3rem'}}>
    
    <tr>
      <th scope="col">tododata</th>
    </tr>
    {todolist.map((data:any)=> (<><thead className="table-dark">
    </thead>
    <tbody>
    <tr>
      <td className="d-flex justify-content-between">
        <span>  {data.todoData}</span>
        <a  style={{textDecoration:"none"}} href="" onClick={()=>updateTask(data)}>🖊️</a>
        <a  style={{textDecoration:"none"}} href="" onClick={()=>deleteTask(data)} >❌</a>
      </td>
    </tr>
    </tbody>
    </>
))}
  </table>
}
</div>
  
</>

    )
}
export default TodoList;

// NotesUI/src/app/WebModule/todolist/todolist.component.ts
import {Component, OnInit} from '@angular/core';
import {Todolist} from "../../types/todolist";
import {TodolistService} from "../../service/todolist.service";

import {Router, Routes} from "@angular/router";

class TodolistSearch {
  todoData: String | undefined;
  userId : String | undefined;
}

@Component({
  selector: 'app-todolist',
  templateUrl: './todolist.component.html',
  styleUrls: ['./todolist.component.css']
})
export class TodolistComponent implements OnInit{
  notFoundshow = false;
  private userid: BigInt =0n;

constructor(private todoservice : TodolistService,private routes : Router) {
}
 updataPlaceHolder :string = "";

  showUpdate=  false;
  idTodo :string ="";
  textUpdate : string ="default value";
  searchlist : Todolist[]|undefined;
  todoUpdate : Todolist ={id: "", todoData: "", userId: "" ,datecreated : "",datedeadline :''}
  addUpdate: string ="";
  showAdd= false;
  searcher: TodolistSearch = { todoData: "", userId: ""};

  searchTableshow= false;

  ngOnInit(): void {
    this.todoservice.setUserid().subscribe(res=>{
      this.userid = res;
      this.getting();
    })
  }
 getting(){
    this.notFoundshow = false;

    this.searchTableshow = true;
    this.todoservice.findAll(this.userid).subscribe(res=>{
      console.log("result" ,res);
      this.searchlist = res;
      this.showAdd = false;
      this.showUpdate = false;
      console.log("todolist   " + this.searchlist);
    })
 }


  delete(id : string) {
    this.todoservice.delete(id).subscribe((res:any)=>
    {
      console.log(res);
    });
    this.routes.navigateByUrl('/',{skipLocationChange:true}).then(()=>{
      this.routes.navigate(['/dashboard/todolist'])
    })

  }

  update(id:string,tododata:string) {
    this.textUpdate = tododata;
    this.updataPlaceHolder = tododata;
    this.searchTableshow = false;
    this.showAdd = false;
    this.showUpdate = true;
    this.idTodo = id;
    }

  updateList() {
    this.todoUpdate.id = this.idTodo;
    this.todoUpdate.todoData = this.textUpdate;
    this.todoUpdate.userId = String(this.userid);
    this.todoservice.update(this.todoUpdate).subscribe(res=>{
        console.log(res);
      }
    )
    this.routes.navigateByUrl('/',{skipLocationChange:true}).then(()=>{
      this.routes.navigate(['/dashboard/todolist']);
    })
    // window.location.reload();
  }

  addListCall() {
    this.notFoundshow = false;

    this.searchTableshow = false;
    this.showUpdate = false;
    this.showAdd = true;
  }

  addList() {
    this.todoUpdate.todoData = this.addUpdate;
    this.todoUpdate.userId = String(this.userid);
    this.showUpdate = false;
    this.todoservice.add(this.todoUpdate).subscribe(res=>{
      console.log("result" + res);
    })
    // this.routes.navigateByUrl('/',{skipLocationChange:true}).then(()=>{
    //   this.routes.navigate(['/dashboard/todolist']);
    // })
    this.routes.navigateByUrl('/',{skipLocationChange:true}).then(()=>{
      this.routes.navigate(['/dashboard/todolist']);
    })
  }

  searcherfunc() {
      this.showUpdate = false;
      this.showAdd = false;
      this.searcher.userId = String(this.userid);
      this.todoservice.search(this.searcher).subscribe(res => {
        console.log(res);
        this.searchlist = res;
        if (this.searchlist.length == 0) {
          this.notFoundshow = true;
          this.searchTableshow = false;
        } else {
          this.notFoundshow = false;
          this.searchTableshow = true;
        }
      });
    }

}


<div class="container p-5">
  <div class="input-group">
  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" [(ngModel)]="searcher.todoData" >
    <button  class="btn border-0" (click)="searcherfunc()"><i class="bi bi-search" style="font-size: 1.5rem;"></i></button>
  </div>
    <div *ngIf="notFoundshow"  class="container border-dark border-3 rounded " style="margin-top: 3rem">
    <h5 class="border-dark bg-danger rounded opacity-25 display-6" >not found ! </h5>
      <button (click)="addListCall()" class="btn btn-outline-dark ">Add Tasks</button>
  </div>
  <table class="table table-light" *ngIf="mainTableShow" style="margin-top: 3rem">
    <thead class="table-dark">
    <tr>
      <th scope="col">tododata
        <a (click)="addListCall()"><i class="bi bi-file-earmark-plus-fill"></i></a></th>
    </tr>
    </thead>
    <tbody *ngFor = "let todo of todolist">
    <tr class="justify-content-evenly">
<!--      <th scope="row">{{todo.id}}</th>-->
      <td class="justify-content-evenly">{{todo.todoData}} <span class="p-1"><a (click)="delete(todo.id)" ><i class="bi bi-dash-circle p-2" ></i></a> <a (click)="update(todo.id,todo.todoData)"><i class="bi bi-pencil-fill p-2"></i></a> </span></td>
<!--      <td>{{todo.datecreated}}</td>-->
<!--      <td>{{todo.datedeadline}}</td>-->
    </tr>
    </tbody>
  </table>
<!--  <div class="container" *ngIf="showUpdate" style="padding-top: 3rem">-->
<!--    <div class="input-group">-->
<!--      <input type="text"  style="margin-left: 40%" placeholder="{{updataPlaceHolder }}" [(ngModel)]="textUpdate">-->
<!--      <button class=" btn btn-outline-danger" (click)="updateList()">update</button>-->
<!--    </div>-->
<!--  </div>-->
  <form (ngSubmit)="updateList()" #noteForm="ngForm" *ngIf="showUpdate">
    <div>

      <input  style="margin:1rem;text-align: center; width: 12rem; height: 2rem; box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); background-color: #fafafa;"
              type="text"
              [value] = "textUpdate"
              id="noteUpdateHeading"
              name="noteHeading"
              [(ngModel)]="textUpdate"
              #title="ngModel"
              required
              minlength="1"

      >
<!--      mon-->

      <div class="text-warning m-2" *ngIf="title.invalid && (title.dirty||title.touched)">Task is required</div>
    </div>
    <button type="submit" class="btn btn-primary" [disabled]="noteForm.invalid">Update task</button>
  </form>
<!--  <div class="container" *ngIf="showAdd" style="margin-top: 3rem; align-items: center">-->
<!--    <div class="input-group">-->
<!--    <input type="text"  style="margin-left: 40%" placeholder="Add tasks here" [(ngModel)]="addUpdate">-->
<!--    <button class=" btn btn-outline-warning" (click)="addList()">Add</button>-->
<!--  </div>-->
<!--  </div>-->
  <form (ngSubmit)="addList()" #noteForm="ngForm" *ngIf="showAdd">
    <div>

      <input  style="margin:1rem;text-align: center; width: 12rem; height: 2rem; box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); background-color: #fafafa;"
              placeholder="add tasks here"
              type="text"
              id="noteHeading"
              name="noteHeading"
              [(ngModel)]="addUpdate"
              #title="ngModel"
              required
              minlength="1"

      >

      <div class="text-success m-2" *ngIf="title.invalid && (title.dirty||title.touched)">Task is required</div>
    </div>
    <button type="submit" class="btn btn-dark" [disabled]="noteForm.invalid">Add task</button>
  </form>
  <table class="table table-light" *ngIf="searchTableshow" style="margin-top: 3rem">
    <thead class="table-dark">
    <tr>
<!--      <th scope="col">#</th>-->
      <th scope="col">tododata

        <a (click)="addListCall()"><i class="bi bi-file-earmark-plus-fill"></i></a></th>
    </tr>
    </thead>
    <tbody *ngFor = "let todo of searchlist">
    <tr>
<!--      <th scope="row">{{todo.id}}</th>-->
      <td>{{todo.todoData}} <span class="p-1"><a (click)="delete(todo.id)" ><i class="bi bi-dash-circle p-2" ></i></a> <a (click)="update(todo.id,todo.todoData)"><i class="bi bi-pencil-fill p-2"></i></a> </span></td>
    </tr>
    </tbody>
  </table>
</div>
